# Generated by Django 5.0.3 on 2024-10-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coti', '0002_alter_usuarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cotizaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallecotizaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
